apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-app
  labels:
    app: slack-app
spec:
  selector:
    matchLabels:
      app: slack-app
  replicas: 1
  template:
    metadata:
      labels:
        app: slack-app
    spec:
      containers:
      - name: slack-app
        image: gcr.io/zeebe-io/slack-app:latest
        imagePullPolicy: Always
        # https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
        env:
          - name: CLOUD_CLIENTID
            valueFrom:
              secretKeyRef:
                name: slack-app-secret
                key: clientId
          - name: CLOUD_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: slack-app-secret
                key: clientSecret
          - name: CLOUD_AUTHSERVER
            valueFrom:
              secretKeyRef:
                name: slack-app-secret
                key: authServer
          - name: CLOUD_CONTACTPOINT
            valueFrom:
              secretKeyRef:
                name: slack-app-secret
                key: contactPoint
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: slack-app-secret
                key: slackToken
---

apiVersion: v1
kind: Service
metadata:
  name: slack-app-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: slack-app
  type: NodePort
